---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: atomic-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 44 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
      - https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
    install:
      - brave-origin
      - qemu-kvm
      - libvirt
      - virt-install
      - virt-manager
      - vlc
      - gstreamer1-plugins-base
      - gstreamer1-plugins-good
      - gstreamer1-plugins-bad-free
      - gstreamer1-plugins-ugly
      - gstreamer1-plugin-libav
      - ffmpeg
      - intel-media-driver
    remove:
      - firefox
      - firefox-langpacks
  - type: dnf
    install:
      packages:
        - fastfetch
        - gparted
        - brave-origin
        - git
  - type: bling
    install:
      - 1password
  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.github.tchx84.Flatseal
          - io.github.flattool.Warehouse
          - org.onlyoffice.desktopeditors
          - io.missioncenter.MissionCenter
          - com.rustdesk.RustDesk
          - io.ente.auth
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
